### ISSUE TITLE
执行LoginWindow报错

### ISSUE THREAD

**Issue by hwdtdd** [xialeistudio/mybatis-generator-gui#2]
没玩过swing，费半天劲用exe4j打包好了之后执行报错如下：
Exception in thread "main" java.lang.NullPointerException
    at com.ddhigh.mybatis.window.LoginWindow.<init>(LoginWindow.java:27)
    at com.ddhigh.mybatis.window.LoginWindow.main(LoginWindow.java:98)

**Comment by xialeistudio** [comment]
请使用 javaw 运行主程序jar
