### ISSUE TITLE
源码直接运行不起来

### ISSUE THREAD

**Issue by jacky8466** [xialeistudio/mybatis-generator-gui#3]
Exception in thread "main" java.lang.NullPointerException
	at com.ddhigh.mybatis.window.LoginWindow.<init>(LoginWindow.java:27)
	at com.ddhigh.mybatis.window.LoginWindow.main(LoginWindow.java:98)

麻烦给个运行步骤啊

**Comment by xialeistudio** [comment]
你用的什么IDE

**Comment by jacky8466** [comment]
myeclipse/eclipse

**Comment by xialeistudio** [comment]
源码依赖idea 的ide😘


发自我的 iPhone

**Comment by jacky8466** [comment]
@xialeistudio 能不能搞个eclipse/myeclipse的出来，idea虽然智能，但不是大众普世的啊
